begin
CREATE CONSTRAINT ON (n:User) ASSERT n.name IS UNIQUE;
CREATE CONSTRAINT ON (n:User) ASSERT n.alias IS UNIQUE;
CREATE CONSTRAINT ON (n:LdapUser) ASSERT n.cn IS UNIQUE;
CREATE CONSTRAINT ON (n:LdapUser) ASSERT n.dn IS UNIQUE;
CREATE CONSTRAINT ON (n:Role) ASSERT n.name IS UNIQUE;
commit